// File generated by FlutterFire CLI.
// ignore\_for\_file: type=lint
import 'package\:firebase\_core/firebase\_core.dart' show FirebaseOptions;
import 'package\:flutter\_dotenv/flutter\_dotenv.dart';
import 'package\:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default \[FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// `dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// `
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKi0ElxD6bzldpypysx5-kEh-MLHqnAL4',
    appId: '1:470058460441\:web:90d7aed785c2b94598d188',
    messagingSenderId: '470058460441',
    projectId: 'event-reminder-app-e3b42',
    authDomain: 'event-reminder-app-e3b42.firebaseapp.com',
    storageBucket: 'event-reminder-app-e3b42.firebasestorage.app',
    measurementId: 'G-RZ70JH4SEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMGDBDN9eMtogjC6tfxgFaFe8iWHKLz5g',
    appId: '1:470058460441\:android\:db70261f43be2f2998d188',
    messagingSenderId: '470058460441',
    projectId: 'event-reminder-app-e3b42',
    storageBucket: 'event-reminder-app-e3b42.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKi0ElxD6bzldpypysx5-kEh-MLHqnAL4',
    appId: '1:470058460441\:web:90d7aed785c2b94598d188',
    messagingSenderId: '470058460441',
    projectId: 'event-reminder-app-e3b42',
    authDomain: 'event-reminder-app-e3b42.firebaseapp.com',
    storageBucket: 'event-reminder-app-e3b42.firebasestorage.app',
    measurementId: 'G-RZ70JH4SEF',
  );
}
